sudo: required
services:
  - docker

before_install:
  - docker build -t maheshsuthari/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run maheshsuthari/react-test npm test -- --coverage
after_success:
  - docker build -t maheshsuthari/multi-client ./client
  - docker build -t maheshsuthari/multi-nginx ./nginx
  - docker build -t maheshsuthari/multi-server ./server
  - docker build -t maheshsuthari/multi-worker ./worker
  #login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push maheshsuthari/multi-client
  - docker push maheshsuthari/multi-nginx
  - docker push maheshsuthari/multi-server
  - docker push maheshsuthari/multi-worker  